packages:
- apps/*
- configs/*
- design/*
- packages/*
catalogs:
  common:
    '@fontsource/rubik': 5.2.8
    barrelsby: 2.8.1
    cross-env: 10.0.0
    move-cli: 2.0.0
    rimraf: 6.0.1
  design:
    '@fontsource/rubik': 5.2.8
    '@heroicons/react': 2.2.0
    '@heroui/react': 2.8.5
    'style-dictionary': 5.0.4
  eslint:
    '@eslint/js': 9.35.0
    eslint: 9.35.0
    eslint-config-prettier: 10.1.8
    eslint-plugin-formatjs: 5.4.2
    eslint-plugin-import: 2.32.0
    eslint-plugin-prettier: 5.5.4
    eslint-plugin-react: 7.37.5
    eslint-plugin-react-compiler: 19.1.0-rc.2
    eslint-plugin-react-hooks: 5.2.0
    eslint-plugin-storybook: 9.1.10
    typescript-eslint: 8.42.0
  mocks:
    '@mocks-server/admin-api-client': 7.0.1
    '@mocks-server/admin-api-paths': 5.0.0
    '@mocks-server/main': 4.1.0
  playwright:
    '@playwright/test': 1.55.0
    playwright: 1.55.0
  react19:
    '@types/react': 19.1.12
    '@types/react-dom': 19.1.9
    babel-plugin-react-compiler: 19.1.0-rc.3
    react: 19.1.1
    react-dom: 19.1.1
  storybook:
    '@storybook/addon-a11y': 9.1.10
    '@storybook/addon-docs': 9.1.10
    '@storybook/addon-themes': 9.1.10
    '@storybook/addon-vitest': 9.1.10
    '@storybook/builder-vite': 9.1.10
    '@storybook/react': 9.1.10
    '@storybook/react-vite': 9.1.10
    storybook: 9.1.10
  tailwind:
    tailwindcss: 4.1.13
    '@tailwindcss/aspect-ratio': 0.4.2
    '@tailwindcss/typography': 0.5.19
    '@tailwindcss/vite': 4.1.13
  typescript:
    typescript: 5.9.3
  validation:
    '@hookform/resolvers': 5.2.2
    zod: 4.1.12
  vite:
    '@vitejs/plugin-basic-ssl': 2.1.0
    '@vitejs/plugin-react': 4.7.0
    vite: 7.1.9
    vite-tsconfig-paths: 5.1.4
    vite-plugin-http2-proxy: 0.5.1
    vite-plugin-pwa: 1.0.3
  vitest:
    vitest: 3.2.4
    '@vitest/browser': 3.2.4
    '@vitest/coverage-v8': 3.2.4
