packages:
- apps/*
- configs/*
- packages/*
catalogs:
  common:
    '@fontsource/rubik': 5.2.5
    cross-env: 7.0.3
    move-cli: 2.0.0
    rimraf: 6.0.1
  eslint:
    '@eslint/js': 9.27.0
    eslint: 9.27.0
    eslint-config-prettier: 10.1.5
    eslint-plugin-formatjs: 5.3.1
    eslint-plugin-import: 2.31.0
    eslint-plugin-prettier: 5.4.0
    eslint-plugin-react: 7.37.5
    eslint-plugin-react-compiler: 19.0.0-beta-ebf51a3-20250411
    eslint-plugin-react-hooks: 5.2.0
    eslint-plugin-storybook: 0.12.0
    typescript-eslint: 8.32.1
  mocks:
    '@mocks-server/admin-api-client': 7.0.1
    '@mocks-server/admin-api-paths': 5.0.0
    '@mocks-server/main': 4.1.0
  playwright:
    '@playwright/test': 1.52.0
    playwright: 1.52.0
  react19:
    '@types/react': 19.1.8
    '@types/react-dom': 19.1.6
    react: 19.1.0
    react-dom: 19.1.0
  storybook:
    '@storybook/addon-themes': 9.0.12
    '@storybook/addon-vitest': 9.0.12
    '@storybook/builder-vite': 9.0.12
    '@storybook/react': 9.0.12
    '@storybook/react-vite': 9.0.12
    storybook: 9.0.12
  tailwind:
    tailwindcss: 4.1.10
    '@tailwindcss/aspect-ratio': 0.4.2
    '@tailwindcss/typography': 0.5.16
    '@tailwindcss/vite': 4.1.10
  typescript:
    typescript: 5.8.3
  validation:
    '@hookform/resolvers': 5.0.1
    zod: 3.24.2
  vite:
    '@vitejs/plugin-react': 4.5.0
    vite: 6.3.5
    vite-tsconfig-paths: 5.1.4
    vite-plugin-http2-proxy: 0.5.0
    vite-plugin-mkcert: 1.17.8
    vite-plugin-pwa: 1.0.0
  vitest:
    vitest: 3.2.3
    '@vitest/browser': 3.2.3
    '@vitest/coverage-v8': 3.2.3
