packages:
- apps/*
- configs/*
- design/*
- packages/*
catalogs:
  common:
    '@fontsource/rubik': 5.2.8
    barrelsby: 2.8.1
    cross-env: 10.1.0
    move-cli: 2.0.0
    rimraf: 6.1.2
  design:
    '@fontsource/rubik': 5.2.8
    '@heroicons/react': 2.2.0
    '@heroui/react': 2.8.9
    'style-dictionary': 5.3.0
  eslint:
    '@eslint/js': 10.0.1
    eslint: 10.0.1
    eslint-config-prettier: 10.1.8
    eslint-plugin-formatjs: 6.1.3
    eslint-plugin-import: 2.32.0
    eslint-plugin-prettier: 5.5.5
    eslint-plugin-react: 7.37.5
    eslint-plugin-react-compiler: 19.1.0-rc.2
    eslint-plugin-react-hooks: 7.0.1
    eslint-plugin-storybook: 10.2.8
    typescript-eslint: 8.55.0
  mocks:
    '@mocks-server/admin-api-client': 7.0.1
    '@mocks-server/admin-api-paths': 5.0.0
    '@mocks-server/main': 4.1.0
  playwright:
    '@playwright/test': 1.58.2
    playwright: 1.58.2
  react19:
    '@types/react': 19.2.14
    '@types/react-dom': 19.2.3
    babel-plugin-react-compiler: 19.1.0-rc.3
    react: 19.2.4
    react-dom: 19.2.4
  storybook:
    '@storybook/addon-a11y': 10.2.8
    '@storybook/addon-docs': 10.2.8
    '@storybook/addon-themes': 10.2.8
    '@storybook/addon-vitest': 10.2.8
    '@storybook/builder-vite': 10.2.8
    '@storybook/react': 10.2.8
    '@storybook/react-vite': 10.2.8
    storybook: 10.2.8
  tailwind:
    tailwindcss: 4.1.18
    '@tailwindcss/aspect-ratio': 0.4.2
    '@tailwindcss/typography': 0.5.19
    '@tailwindcss/vite': 4.1.18
  typescript:
    typescript: 5.9.3
  validation:
    '@hookform/resolvers': 5.2.2
    zod: 4.3.6
  vite:
    '@vitejs/plugin-basic-ssl': 2.1.4
    '@vitejs/plugin-react': 4.7.0
    vite: 7.3.1
    vite-tsconfig-paths: 6.1.1
    vite-plugin-http2-proxy: 0.5.1
    vite-plugin-pwa: 1.2.0
  vitest:
    vitest: 3.2.4
    '@vitest/browser': 3.2.4
    '@vitest/coverage-v8': 3.2.4
