packages:
- apps/*
- configs/*
- design/*
- packages/*
catalogs:
  common:
    '@fontsource/rubik': 5.2.6
    barrelsby: 2.8.1
    cross-env: 7.0.3
    move-cli: 2.0.0
    rimraf: 6.0.1
  design:
    '@fontsource/rubik': 5.2.6
    '@heroicons/react': 2.2.0
    '@heroui/react': 2.8.1
    'style-dictionary': 5.0.1
  eslint:
    '@eslint/js': 9.31.0
    eslint: 9.31.0
    eslint-config-prettier: 10.1.8
    eslint-plugin-formatjs: 5.4.0
    eslint-plugin-import: 2.32.0
    eslint-plugin-prettier: 5.5.3
    eslint-plugin-react: 7.37.5
    eslint-plugin-react-compiler: 19.1.0-rc.2
    eslint-plugin-react-hooks: 5.2.0
    eslint-plugin-storybook: 9.0.17
    typescript-eslint: 8.37.0
  mocks:
    '@mocks-server/admin-api-client': 7.0.1
    '@mocks-server/admin-api-paths': 5.0.0
    '@mocks-server/main': 4.1.0
  playwright:
    '@playwright/test': 1.54.1
    playwright: 1.54.1
  react19:
    '@types/react': 19.1.8
    '@types/react-dom': 19.1.6
    babel-plugin-react-compiler: 19.1.0-rc.2
    react: 19.1.0
    react-dom: 19.1.0
  storybook:
    '@storybook/addon-a11y': 9.0.17
    '@storybook/addon-docs': 9.0.17
    '@storybook/addon-themes': 9.0.17
    '@storybook/addon-vitest': 9.0.17
    '@storybook/builder-vite': 9.0.17
    '@storybook/react': 9.0.17
    '@storybook/react-vite': 9.0.17
    storybook: 9.0.17
  tailwind:
    tailwindcss: 4.1.11
    '@tailwindcss/aspect-ratio': 0.4.2
    '@tailwindcss/typography': 0.5.16
    '@tailwindcss/vite': 4.1.11
  typescript:
    typescript: 5.8.3
  validation:
    '@hookform/resolvers': 5.1.1
    zod: 3.25.76
  vite:
    '@vitejs/plugin-basic-ssl': 2.1.0
    '@vitejs/plugin-react': 4.7.0
    vite: 6.3.5
    vite-tsconfig-paths: 5.1.4
    vite-plugin-http2-proxy: 0.5.0
    vite-plugin-pwa: 1.0.1
  vitest:
    vitest: 3.2.4
    '@vitest/browser': 3.2.4
    '@vitest/coverage-v8': 3.2.4
