packages:
- apps/*
- configs/*
- design/*
- packages/*
catalogs:
  common:
    '@fontsource/rubik': 5.2.8
    barrelsby: 2.8.1
    cross-env: 10.1.0
    move-cli: 2.0.0
    rimraf: 6.1.0
  design:
    '@fontsource/rubik': 5.2.8
    '@heroicons/react': 2.2.0
    '@heroui/react': 2.8.5
    'style-dictionary': 5.1.1
  eslint:
    '@eslint/js': 9.39.0
    eslint: 9.39.0
    eslint-config-prettier: 10.1.8
    eslint-plugin-formatjs: 5.4.2
    eslint-plugin-import: 2.32.0
    eslint-plugin-prettier: 5.5.4
    eslint-plugin-react: 7.37.5
    eslint-plugin-react-compiler: 19.1.0-rc.2
    eslint-plugin-react-hooks: 7.0.1
    eslint-plugin-storybook: 10.0.2
    typescript-eslint: 8.46.2
  mocks:
    '@mocks-server/admin-api-client': 7.0.1
    '@mocks-server/admin-api-paths': 5.0.0
    '@mocks-server/main': 4.1.0
  playwright:
    '@playwright/test': 1.56.1
    playwright: 1.56.1
  react19:
    '@types/react': 19.2.2
    '@types/react-dom': 19.2.2
    babel-plugin-react-compiler: 19.1.0-rc.3
    react: 19.2.0
    react-dom: 19.2.0
  storybook:
    '@storybook/addon-a11y': 10.0.2
    '@storybook/addon-docs': 10.0.2
    '@storybook/addon-themes': 10.0.2
    '@storybook/addon-vitest': 10.0.2
    '@storybook/builder-vite': 10.0.2
    '@storybook/react': 10.0.2
    '@storybook/react-vite': 10.0.2
    storybook: 10.0.2
  tailwind:
    tailwindcss: 4.1.16
    '@tailwindcss/aspect-ratio': 0.4.2
    '@tailwindcss/typography': 0.5.19
    '@tailwindcss/vite': 4.1.16
  typescript:
    typescript: 5.9.3
  validation:
    '@hookform/resolvers': 5.2.2
    zod: 4.1.12
  vite:
    '@vitejs/plugin-basic-ssl': 2.1.0
    '@vitejs/plugin-react': 4.7.0
    vite: 7.1.12
    vite-tsconfig-paths: 5.1.4
    vite-plugin-http2-proxy: 0.5.1
    vite-plugin-pwa: 1.1.0
  vitest:
    vitest: 4.0.6
    '@vitest/browser': 4.0.6
    '@vitest/coverage-v8': 4.0.6
