import { heroui } from "@heroui/react";
import type { Config } from "tailwindcss";
import {
  // Light theme colors
  ColorThemeLightPrimary50,
  ColorThemeLightPrimary100,
  ColorThemeLightPrimary200,
  ColorThemeLightPrimary300,
  ColorThemeLightPrimary400,
  ColorThemeLightPrimary500,
  ColorThemeLightPrimary600,
  ColorThemeLightPrimary700,
  ColorThemeLightPrimary800,
  ColorThemeLightPrimary900,
  ColorThemeLightPrimaryDefault,
  ColorThemeLightPrimaryForeground,
  ColorThemeLightSecondary50,
  ColorThemeLightSecondary100,
  ColorThemeLightSecondary200,
  ColorThemeLightSecondary300,
  ColorThemeLightSecondary400,
  ColorThemeLightSecondary500,
  ColorThemeLightSecondary600,
  ColorThemeLightSecondary700,
  ColorThemeLightSecondary800,
  ColorThemeLightSecondary900,
  ColorThemeLightSecondaryDefault,
  ColorThemeLightSecondaryForeground,
  // Dark theme colors
  ColorThemeDarkPrimary50,
  ColorThemeDarkPrimary100,
  ColorThemeDarkPrimary200,
  ColorThemeDarkPrimary300,
  ColorThemeDarkPrimary400,
  ColorThemeDarkPrimary500,
  ColorThemeDarkPrimary600,
  ColorThemeDarkPrimary700,
  ColorThemeDarkPrimary800,
  ColorThemeDarkPrimary900,
  ColorThemeDarkPrimaryDefault,
  ColorThemeDarkPrimaryForeground,
  ColorThemeDarkSecondary50,
  ColorThemeDarkSecondary100,
  ColorThemeDarkSecondary200,
  ColorThemeDarkSecondary300,
  ColorThemeDarkSecondary400,
  ColorThemeDarkSecondary500,
  ColorThemeDarkSecondary600,
  ColorThemeDarkSecondary700,
  ColorThemeDarkSecondary800,
  ColorThemeDarkSecondary900,
  ColorThemeDarkSecondaryDefault,
  ColorThemeDarkSecondaryForeground,
} from "@config/design-tokens/tailwind";

const config = heroui({
  themes: {
    light: {
      colors: {
        primary: {
          50: ColorThemeLightPrimary50,
          100: ColorThemeLightPrimary100,
          200: ColorThemeLightPrimary200,
          300: ColorThemeLightPrimary300,
          400: ColorThemeLightPrimary400,
          500: ColorThemeLightPrimary500,
          600: ColorThemeLightPrimary600,
          700: ColorThemeLightPrimary700,
          800: ColorThemeLightPrimary800,
          900: ColorThemeLightPrimary900,
          DEFAULT: ColorThemeLightPrimaryDefault,
          foreground: ColorThemeLightPrimaryForeground,
        },
        secondary: {
          50: ColorThemeLightSecondary50,
          100: ColorThemeLightSecondary100,
          200: ColorThemeLightSecondary200,
          300: ColorThemeLightSecondary300,
          400: ColorThemeLightSecondary400,
          500: ColorThemeLightSecondary500,
          600: ColorThemeLightSecondary600,
          700: ColorThemeLightSecondary700,
          800: ColorThemeLightSecondary800,
          900: ColorThemeLightSecondary900,
          DEFAULT: ColorThemeLightSecondaryDefault,
          foreground: ColorThemeLightSecondaryForeground,
        },
      },
    },
    dark: {
      colors: {
        primary: {
          50: ColorThemeDarkPrimary50,
          100: ColorThemeDarkPrimary100,
          200: ColorThemeDarkPrimary200,
          300: ColorThemeDarkPrimary300,
          400: ColorThemeDarkPrimary400,
          500: ColorThemeDarkPrimary500,
          600: ColorThemeDarkPrimary600,
          700: ColorThemeDarkPrimary700,
          800: ColorThemeDarkPrimary800,
          900: ColorThemeDarkPrimary900,
          DEFAULT: ColorThemeDarkPrimaryDefault,
          foreground: ColorThemeDarkPrimaryForeground,
        },
        secondary: {
          50: ColorThemeDarkSecondary50,
          100: ColorThemeDarkSecondary100,
          200: ColorThemeDarkSecondary200,
          300: ColorThemeDarkSecondary300,
          400: ColorThemeDarkSecondary400,
          500: ColorThemeDarkSecondary500,
          600: ColorThemeDarkSecondary600,
          700: ColorThemeDarkSecondary700,
          800: ColorThemeDarkSecondary800,
          900: ColorThemeDarkSecondary900,
          DEFAULT: ColorThemeDarkSecondaryDefault,
          foreground: ColorThemeDarkSecondaryForeground,
        },
      },
    },
  },
}) as Config;

export default config;
