import { heroui } from "@heroui/react";
import type { Config } from "tailwindcss";
import {
  // Light theme colors
  ColorThemeLightDefault50,
  ColorThemeLightDefault100,
  ColorThemeLightDefault200,
  ColorThemeLightDefault300,
  ColorThemeLightDefault400,
  ColorThemeLightDefault500,
  ColorThemeLightDefault600,
  ColorThemeLightDefault700,
  ColorThemeLightDefault800,
  ColorThemeLightDefault900,
  ColorThemeLightDefaultDefault,
  ColorThemeLightDefaultForeground,
  ColorThemeLightPrimary50,
  ColorThemeLightPrimary100,
  ColorThemeLightPrimary200,
  ColorThemeLightPrimary300,
  ColorThemeLightPrimary400,
  ColorThemeLightPrimary500,
  ColorThemeLightPrimary600,
  ColorThemeLightPrimary700,
  ColorThemeLightPrimary800,
  ColorThemeLightPrimary900,
  ColorThemeLightPrimaryDefault,
  ColorThemeLightPrimaryForeground,
  ColorThemeLightSecondary50,
  ColorThemeLightSecondary100,
  ColorThemeLightSecondary200,
  ColorThemeLightSecondary300,
  ColorThemeLightSecondary400,
  ColorThemeLightSecondary500,
  ColorThemeLightSecondary600,
  ColorThemeLightSecondary700,
  ColorThemeLightSecondary800,
  ColorThemeLightSecondary900,
  ColorThemeLightSecondaryDefault,
  ColorThemeLightSecondaryForeground,
  ColorThemeLightSuccess50,
  ColorThemeLightSuccess100,
  ColorThemeLightSuccess200,
  ColorThemeLightSuccess300,
  ColorThemeLightSuccess400,
  ColorThemeLightSuccess500,
  ColorThemeLightSuccess600,
  ColorThemeLightSuccess700,
  ColorThemeLightSuccess800,
  ColorThemeLightSuccess900,
  ColorThemeLightSuccessDefault,
  ColorThemeLightSuccessForeground,
  ColorThemeLightWarning50,
  ColorThemeLightWarning100,
  ColorThemeLightWarning200,
  ColorThemeLightWarning300,
  ColorThemeLightWarning400,
  ColorThemeLightWarning500,
  ColorThemeLightWarning600,
  ColorThemeLightWarning700,
  ColorThemeLightWarning800,
  ColorThemeLightWarning900,
  ColorThemeLightWarningDefault,
  ColorThemeLightWarningForeground,
  ColorThemeLightDanger50,
  ColorThemeLightDanger100,
  ColorThemeLightDanger200,
  ColorThemeLightDanger300,
  ColorThemeLightDanger400,
  ColorThemeLightDanger500,
  ColorThemeLightDanger600,
  ColorThemeLightDanger700,
  ColorThemeLightDanger800,
  ColorThemeLightDanger900,
  ColorThemeLightDangerDefault,
  ColorThemeLightDangerForeground,
  ColorThemeLightBackground,
  ColorThemeLightForeground,
  ColorThemeLightContent1Default,
  ColorThemeLightContent1Foreground,
  ColorThemeLightContent2Default,
  ColorThemeLightContent2Foreground,
  ColorThemeLightContent3Default,
  ColorThemeLightContent3Foreground,
  ColorThemeLightContent4Default,
  ColorThemeLightContent4Foreground,
  ColorThemeLightFocus,
  ColorThemeLightOverlay,
  // Dark theme colors
  ColorThemeDarkDefault50,
  ColorThemeDarkDefault100,
  ColorThemeDarkDefault200,
  ColorThemeDarkDefault300,
  ColorThemeDarkDefault400,
  ColorThemeDarkDefault500,
  ColorThemeDarkDefault600,
  ColorThemeDarkDefault700,
  ColorThemeDarkDefault800,
  ColorThemeDarkDefault900,
  ColorThemeDarkDefaultDefault,
  ColorThemeDarkDefaultForeground,
  ColorThemeDarkPrimary50,
  ColorThemeDarkPrimary100,
  ColorThemeDarkPrimary200,
  ColorThemeDarkPrimary300,
  ColorThemeDarkPrimary400,
  ColorThemeDarkPrimary500,
  ColorThemeDarkPrimary600,
  ColorThemeDarkPrimary700,
  ColorThemeDarkPrimary800,
  ColorThemeDarkPrimary900,
  ColorThemeDarkPrimaryDefault,
  ColorThemeDarkPrimaryForeground,
  ColorThemeDarkSecondary50,
  ColorThemeDarkSecondary100,
  ColorThemeDarkSecondary200,
  ColorThemeDarkSecondary300,
  ColorThemeDarkSecondary400,
  ColorThemeDarkSecondary500,
  ColorThemeDarkSecondary600,
  ColorThemeDarkSecondary700,
  ColorThemeDarkSecondary800,
  ColorThemeDarkSecondary900,
  ColorThemeDarkSecondaryDefault,
  ColorThemeDarkSecondaryForeground,
  ColorThemeDarkSuccess50,
  ColorThemeDarkSuccess100,
  ColorThemeDarkSuccess200,
  ColorThemeDarkSuccess300,
  ColorThemeDarkSuccess400,
  ColorThemeDarkSuccess500,
  ColorThemeDarkSuccess600,
  ColorThemeDarkSuccess700,
  ColorThemeDarkSuccess800,
  ColorThemeDarkSuccess900,
  ColorThemeDarkSuccessDefault,
  ColorThemeDarkSuccessForeground,
  ColorThemeDarkWarning50,
  ColorThemeDarkWarning100,
  ColorThemeDarkWarning200,
  ColorThemeDarkWarning300,
  ColorThemeDarkWarning400,
  ColorThemeDarkWarning500,
  ColorThemeDarkWarning600,
  ColorThemeDarkWarning700,
  ColorThemeDarkWarning800,
  ColorThemeDarkWarning900,
  ColorThemeDarkWarningDefault,
  ColorThemeDarkWarningForeground,
  ColorThemeDarkDanger50,
  ColorThemeDarkDanger100,
  ColorThemeDarkDanger200,
  ColorThemeDarkDanger300,
  ColorThemeDarkDanger400,
  ColorThemeDarkDanger500,
  ColorThemeDarkDanger600,
  ColorThemeDarkDanger700,
  ColorThemeDarkDanger800,
  ColorThemeDarkDanger900,
  ColorThemeDarkDangerDefault,
  ColorThemeDarkDangerForeground,
  ColorThemeDarkBackground,
  ColorThemeDarkForeground,
  ColorThemeDarkContent1Default,
  ColorThemeDarkContent1Foreground,
  ColorThemeDarkContent2Default,
  ColorThemeDarkContent2Foreground,
  ColorThemeDarkContent3Default,
  ColorThemeDarkContent3Foreground,
  ColorThemeDarkContent4Default,
  ColorThemeDarkContent4Foreground,
  ColorThemeDarkFocus,
  ColorThemeDarkOverlay,
  // Layout
  LayoutDisabledOpacity,
} from "@design/tokens/tailwind";

const config = heroui({
  themes: {
    light: {
      colors: {
        default: {
          50: ColorThemeLightDefault50,
          100: ColorThemeLightDefault100,
          200: ColorThemeLightDefault200,
          300: ColorThemeLightDefault300,
          400: ColorThemeLightDefault400,
          500: ColorThemeLightDefault500,
          600: ColorThemeLightDefault600,
          700: ColorThemeLightDefault700,
          800: ColorThemeLightDefault800,
          900: ColorThemeLightDefault900,
          DEFAULT: ColorThemeLightDefaultDefault,
          foreground: ColorThemeLightDefaultForeground,
        },
        primary: {
          50: ColorThemeLightPrimary50,
          100: ColorThemeLightPrimary100,
          200: ColorThemeLightPrimary200,
          300: ColorThemeLightPrimary300,
          400: ColorThemeLightPrimary400,
          500: ColorThemeLightPrimary500,
          600: ColorThemeLightPrimary600,
          700: ColorThemeLightPrimary700,
          800: ColorThemeLightPrimary800,
          900: ColorThemeLightPrimary900,
          DEFAULT: ColorThemeLightPrimaryDefault,
          foreground: ColorThemeLightPrimaryForeground,
        },
        secondary: {
          50: ColorThemeLightSecondary50,
          100: ColorThemeLightSecondary100,
          200: ColorThemeLightSecondary200,
          300: ColorThemeLightSecondary300,
          400: ColorThemeLightSecondary400,
          500: ColorThemeLightSecondary500,
          600: ColorThemeLightSecondary600,
          700: ColorThemeLightSecondary700,
          800: ColorThemeLightSecondary800,
          900: ColorThemeLightSecondary900,
          DEFAULT: ColorThemeLightSecondaryDefault,
          foreground: ColorThemeLightSecondaryForeground,
        },
        success: {
          50: ColorThemeLightSuccess50,
          100: ColorThemeLightSuccess100,
          200: ColorThemeLightSuccess200,
          300: ColorThemeLightSuccess300,
          400: ColorThemeLightSuccess400,
          500: ColorThemeLightSuccess500,
          600: ColorThemeLightSuccess600,
          700: ColorThemeLightSuccess700,
          800: ColorThemeLightSuccess800,
          900: ColorThemeLightSuccess900,
          DEFAULT: ColorThemeLightSuccessDefault,
          foreground: ColorThemeLightSuccessForeground,
        },
        warning: {
          50: ColorThemeLightWarning50,
          100: ColorThemeLightWarning100,
          200: ColorThemeLightWarning200,
          300: ColorThemeLightWarning300,
          400: ColorThemeLightWarning400,
          500: ColorThemeLightWarning500,
          600: ColorThemeLightWarning600,
          700: ColorThemeLightWarning700,
          800: ColorThemeLightWarning800,
          900: ColorThemeLightWarning900,
          DEFAULT: ColorThemeLightWarningDefault,
          foreground: ColorThemeLightWarningForeground,
        },
        danger: {
          50: ColorThemeLightDanger50,
          100: ColorThemeLightDanger100,
          200: ColorThemeLightDanger200,
          300: ColorThemeLightDanger300,
          400: ColorThemeLightDanger400,
          500: ColorThemeLightDanger500,
          600: ColorThemeLightDanger600,
          700: ColorThemeLightDanger700,
          800: ColorThemeLightDanger800,
          900: ColorThemeLightDanger900,
          DEFAULT: ColorThemeLightDangerDefault,
          foreground: ColorThemeLightDangerForeground,
        },
        background: ColorThemeLightBackground,
        foreground: ColorThemeLightForeground,
        content1: {
          DEFAULT: ColorThemeLightContent1Default,
          foreground: ColorThemeLightContent1Foreground,
        },
        content2: {
          DEFAULT: ColorThemeLightContent2Default,
          foreground: ColorThemeLightContent2Foreground,
        },
        content3: {
          DEFAULT: ColorThemeLightContent3Default,
          foreground: ColorThemeLightContent3Foreground,
        },
        content4: {
          DEFAULT: ColorThemeLightContent4Default,
          foreground: ColorThemeLightContent4Foreground,
        },
        focus: ColorThemeLightFocus,
        overlay: ColorThemeLightOverlay,
      },
    },
    dark: {
      colors: {
        default: {
          50: ColorThemeDarkDefault50,
          100: ColorThemeDarkDefault100,
          200: ColorThemeDarkDefault200,
          300: ColorThemeDarkDefault300,
          400: ColorThemeDarkDefault400,
          500: ColorThemeDarkDefault500,
          600: ColorThemeDarkDefault600,
          700: ColorThemeDarkDefault700,
          800: ColorThemeDarkDefault800,
          900: ColorThemeDarkDefault900,
          DEFAULT: ColorThemeDarkDefaultDefault,
          foreground: ColorThemeDarkDefaultForeground,
        },
        primary: {
          50: ColorThemeDarkPrimary50,
          100: ColorThemeDarkPrimary100,
          200: ColorThemeDarkPrimary200,
          300: ColorThemeDarkPrimary300,
          400: ColorThemeDarkPrimary400,
          500: ColorThemeDarkPrimary500,
          600: ColorThemeDarkPrimary600,
          700: ColorThemeDarkPrimary700,
          800: ColorThemeDarkPrimary800,
          900: ColorThemeDarkPrimary900,
          DEFAULT: ColorThemeDarkPrimaryDefault,
          foreground: ColorThemeDarkPrimaryForeground,
        },
        secondary: {
          50: ColorThemeDarkSecondary50,
          100: ColorThemeDarkSecondary100,
          200: ColorThemeDarkSecondary200,
          300: ColorThemeDarkSecondary300,
          400: ColorThemeDarkSecondary400,
          500: ColorThemeDarkSecondary500,
          600: ColorThemeDarkSecondary600,
          700: ColorThemeDarkSecondary700,
          800: ColorThemeDarkSecondary800,
          900: ColorThemeDarkSecondary900,
          DEFAULT: ColorThemeDarkSecondaryDefault,
          foreground: ColorThemeDarkSecondaryForeground,
        },
        success: {
          50: ColorThemeDarkSuccess50,
          100: ColorThemeDarkSuccess100,
          200: ColorThemeDarkSuccess200,
          300: ColorThemeDarkSuccess300,
          400: ColorThemeDarkSuccess400,
          500: ColorThemeDarkSuccess500,
          600: ColorThemeDarkSuccess600,
          700: ColorThemeDarkSuccess700,
          800: ColorThemeDarkSuccess800,
          900: ColorThemeDarkSuccess900,
          DEFAULT: ColorThemeDarkSuccessDefault,
          foreground: ColorThemeDarkSuccessForeground,
        },
        warning: {
          50: ColorThemeDarkWarning50,
          100: ColorThemeDarkWarning100,
          200: ColorThemeDarkWarning200,
          300: ColorThemeDarkWarning300,
          400: ColorThemeDarkWarning400,
          500: ColorThemeDarkWarning500,
          600: ColorThemeDarkWarning600,
          700: ColorThemeDarkWarning700,
          800: ColorThemeDarkWarning800,
          900: ColorThemeDarkWarning900,
          DEFAULT: ColorThemeDarkWarningDefault,
          foreground: ColorThemeDarkWarningForeground,
        },
        danger: {
          50: ColorThemeDarkDanger50,
          100: ColorThemeDarkDanger100,
          200: ColorThemeDarkDanger200,
          300: ColorThemeDarkDanger300,
          400: ColorThemeDarkDanger400,
          500: ColorThemeDarkDanger500,
          600: ColorThemeDarkDanger600,
          700: ColorThemeDarkDanger700,
          800: ColorThemeDarkDanger800,
          900: ColorThemeDarkDanger900,
          DEFAULT: ColorThemeDarkDangerDefault,
          foreground: ColorThemeDarkDangerForeground,
        },
        background: ColorThemeDarkBackground,
        foreground: ColorThemeDarkForeground,
        content1: {
          DEFAULT: ColorThemeDarkContent1Default,
          foreground: ColorThemeDarkContent1Foreground,
        },
        content2: {
          DEFAULT: ColorThemeDarkContent2Default,
          foreground: ColorThemeDarkContent2Foreground,
        },
        content3: {
          DEFAULT: ColorThemeDarkContent3Default,
          foreground: ColorThemeDarkContent3Foreground,
        },
        content4: {
          DEFAULT: ColorThemeDarkContent4Default,
          foreground: ColorThemeDarkContent4Foreground,
        },
        focus: ColorThemeDarkFocus,
        overlay: ColorThemeDarkOverlay,
      },
    },
  },
  layout: {
    disabledOpacity: LayoutDisabledOpacity,
  },
}) as Config;

export default config;
